name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - oracle_analyzer.py
      - .github/workflows/docker-publish.yml
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker image tags
        id: tags
        run: |
          REPO=ghcr.io/gioppoluca/ora2pg
          if [[ "${{ github.event_name }}" == "release" ]]; then
            TAG=${{ github.event.release.tag_name }}
          else
            TAG=latest
          fi
          echo "IMAGE_TAG=$REPO:$TAG" >> "$GITHUB_OUTPUT"
